services:
  - type: web
    name: strapi
    env: node
    plan: starter
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    healthCheckPath: /_health
    envVars:
      - key: NODE_VERSION
        value: 18.17.0  # Updated to a more recent LTS version
      - key: NODE_ENV
        value: production
      - key: DATABASE_CLIENT
        value: postgres
      - key: DATABASE_HOST
        sync: false  # Allows you to set this in the Render dashboard
      - key: DATABASE_PORT
        value: 5432
      - key: DATABASE_NAME
        sync: false  # Allows you to set this in the Render dashboard
      - key: DATABASE_USERNAME
        sync: false  # Allows you to set this in the Render dashboard
      - key: DATABASE_PASSWORD
        sync: false  # Allows you to set this in the Render dashboard
      - key: DATABASE_SSL
        value: "true"
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: APP_KEYS
        generateValue: true
      - key: API_TOKEN_SALT
        generateValue: true
    autoDeploy: true  # Prevents automatic deployments on every push