services:
  - type: web
    name: strapi
    env: node
    plan: starter
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    healthCheckPath: /_health
    envVars:
      - key: NODE_VERSION
        value: 14.17.0
      - key: NODE_ENV
        value: production
      - key: DATABASE_CLIENT
        value: postgres
      - key: DATABASE_HOST
        value: your_postgres_host
      - key: DATABASE_PORT
        value: 5432
      - key: DATABASE_NAME
        value: your_database_name
      - key: DATABASE_USERNAME
        value: your_database_username
      - key: DATABASE_PASSWORD
        value: your_database_password
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: APP_KEYS
        generateValue: true